from collections.abc import Sequence

import numpy as np

class Affine2d:
    def __init__(self, matrix: Sequence[Sequence[float]] | None = ...): ...
    def get_matrix(self) -> np.ndarray: ...
    def is_diagonal(self) -> bool: ...
    def __call__(self, i: int, j: int) -> float: ...
