from typing import Any

import numpy as np
import numpy.typing as npt

class TrapezoidMapTriFinder:
    def __init__(self, triangulation: Triangulation): ...
    def find_many(self, x: npt.NDArray[np.double], y: npt.NDArray[np.double]) -> npt.NDArray[np.int_]: ...
    def get_tree_stats(self) -> list[int | float]: ...
    def initialize(self) -> None: ...
    def print_tree(self) -> None: ...

class TriContourGenerator:
    def __init__(self, triangulation: Triangulation, z: npt.NDArray[np.double]): ...
    def create_contour(self, level: float) -> tuple[list[npt.NDArray[np.double]], list[npt.NDArray[np.uint8]]]: ...
    def create_filled_contour(self, lower_level: float, upper_level: float) -> tuple[list[npt.NDArray[np.double]], list[npt.NDArray[np.uint8]]]: ...

class Triangulation:
    def __init__(self, x: npt.NDArray[np.double], t: npt.NDArray[np.double], triangles: npt.NDArray[np.int_], mask: npt.NDArray[np.bool_], edges: npt.NDArray[np.int_], neighbors: npt.NDArray[np.int_], correct_triangle_orientations: bool): ...
    def calculate_plane_coefficients(self, z: npt.NDArray[np.double]) -> npt.NDArray[np.double]: ...
    def get_edges(self) -> npt.NDArray[np.int_]: ...
    def get_neighbors(self) -> npt.NDArray[np.int_]: ...
    def set_mask(self, mask: npt.NDArray[np.bool_]) -> None: ...
